[package]
name = "bagipdf"
version = "2.1.1"
description = "BagiPDF - High Performance Portable PDF Tool in Rust & Tauri"
authors = ["Muhammad Fahrizal Rahman"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lopdf = "0.32"
rfd = "0.15"
open = "5.3"

[profile.release]
panic = "abort"
codegen-units = 1
opt-level = "z"
lto = true
strip = true
