directories:
  output: ../dist_electron
  buildResources: build
appId: com.pdfsplitter.pro
productName: PDF Splitter Pro
files:
  - filter:
      - dist/**/*
      - electron.js
win:
  target:
    - nsis
    - portable
  icon: public/vite.svg
portable:
  artifactName: PDFSplitterPro.exe
electronVersion: 34.5.8
