[package]
name = "bagipdf-activate"
version = "1.0.0"
description = "BagiPDF Activate - Client Machine Key Generator Utility"
authors = ["Muhammad Fahrizal Rahman"]
edition = "2021"

[dependencies]
clap        = { version = "4.5", features = ["derive"] }
sha2        = "0.10"
hex         = "0.4"
sysinfo     = "0.32"
mac_address = "1.1"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
